### ISSUE TITLE
function Mariaex.Error.message/1 is undefined

### ISSUE THREAD

**Issue by BenMorganIO** [Dania02525/apartmentex#24]
While tinkering with Apartmentex, I received a warning letting me know that `function Mariaex.Error.message/1 is undefined`.

```
$ mix do deps.get, deps.compile
* Updating apartmentex (https://github.com/BenMorganIO/apartmentex.git)
remote: Counting objects: 3, done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0
From https://github.com/BenMorganIO/apartmentex
 * [new branch]      postgrex-bump -> origin/postgrex-bump
Running dependency resolution
==> fs (compile)
==> ranch (compile)
==> poolboy (compile)
cc -g -O3 -Wall -I/usr/local/Cellar/erlang/18.2.1/lib/erlang/erts-7.2.1/include -Ic_src -fPIC -shared -dynamiclib -undefined dynamic_lookup -o priv/bcrypt_nif.so c_src/bcrypt_nif.c c_src/blowfish.c
==> cowlib (compile)
==> cowboy (compile)
==> apartmentex
Compiling 5 files (.ex)
warning: function Mariaex.Error.message/1 is undefined (module Mariaex.Error is not available)
  lib/apartmentex/tenant_actions.ex:73

Generated apartmentex app
```

**Comment by Dania02525** [comment]
Are you still seeing this error message? It looks like Mariaex.Error.message/1 is a good function that's been around for a couple of years.  I just compiled the latest apartmentex and didn't see the error- here's where it is defined: 

https://github.com/xerions/mariaex/blob/master/lib/mariaex/structs.ex#L27

I wonder if this is caused by the compile order? Anyway, if you aren't experiencing it @BenMorganIO I'll close this one.

**Comment by BenMorganIO** [comment]
I haven't seen this guy in a while. I'm going to close, but if I re-see it I'll reopen and maybe take a crack at solving it.
