### ISSUE TITLE
The one question - is this ready for production?

### ISSUE THREAD

**Issue by kelvinst** [Dania02525/apartmentex#26]
I really didn't want to open an issue for this, but I couldn't find any other way to talk to you. 😶

**Comment by BenMorganIO** [comment]
@kelvinst I've been using for its sugar. If you ever run into an issue where Apartmentex isn't helpful, I'd recommend checking out the [Ecto.Query prefixes](https://hexdocs.pm/ecto/Ecto.Query.html#module-query-prefix).

Since Ecto supports prefixes on its own, I think Apartment will always be production ready since it merely supplies sugar.

Would love to know what @Dania02525 thinks though :)

**Comment by Dania02525** [comment]
@kelvinst to echo what @BenMorganIO said, Apartmentex is really just a wrapper around things that Ecto 2.0 handles- to add convenience to working with multi-schema db.  I'm using the first release in production with Ecto ~1.1, without any issue so I would say barring minor issues that will be immediately apparent, no reason not to use this in production.
