### ISSUE TITLE
Migrating existing tables to multi tenant

### ISSUE THREAD

**Issue by andreapavoni** [Dania02525/apartmentex#30]
Hi there!

I already have a phoenix app with a bunch of tables, it actually works in single tenant mode. I'd like to switch some of these tables to multi tenancy.

My clues on this is the following workflow:

* backup entire database
* move/edit migrations to `priv/MY_REPO/tenant_migrations`
* reset database
* run migrations from scratch
* re-import database data into a specific tenant

I'm just wondering if there's a better/safer/quickier way to do this. Have you got any advice, documentation or book to suggest?

Thanks in advance!

**Comment by Dania02525** [comment]
@andreapavoni That is the safe way to do this.  Doing it the way you described allows you to repeat any step that goes wrong.  That said, you will probably need to modify the pg_dump in order to re-import the tables into a new schema- something like `:set search_path=tenant_1;` at the top of the file should send all the table creation into the schema you specify.

I wouldn't try to alter schema on the tables because it might become difficult to sort out which records in the schema migrations table go with the tenant and which go with the public schema.  when importing the data, be sure you comment out the part in the pg_dump for the schema migrations as you will be generating a clean set of migration records in the new scoped schema migrations table.
